apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ec2-cluster-apr-location
  description: Importing components
spec:
  targets:
    - ./.platform/cluster.yaml
    - ./.platform/spec.yaml
    - ./.platform/infracost.yaml