apiVersion: backstage.io/v1alpha1
kind: Component  #Cluster
metadata:
  name: "ec2-cluster-apr"
  environment:
    cluster_type: ec2
    public_ip: 35.168.76.71
  annotations:
    github.com/project-slug: veecode-platform/ec2-cluster-apr
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,terraform-destroy.yml,deploy_dashboard,infracost.yml
    grafana/dashboard-selector: ec2-cluster-apr
    grafana/alert-label-selector: "alertname=ec2-cluster-apr"
    cluster/instructions: "ssh -i ./key-pair.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} \n\"mkdir -p .kube && k3d kubeconfig get ${CLUSTER_NAME} > ~/.kube/config\"\nscp -i ./key-pair.pem ${EC2_USER}@${EC2_HOST}:~/.kube/config ./config\nyq e 'del(.clusters[0].cluster.certificate-authority-data)' -i ~/.kube/config\nyq e '.clusters[0].cluster.insecure-skip-tls-verify=true' config -i\nyq e '.clusters[0].cluster.server = \"https://${EC2_HOST}:38517\"' config -i\n"
    infracost/project: ec2-cluster-apr
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  #environment: 'environment:default/ec2_environment'
